---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Ticket Iniciar Pruebas
    community.general.jira:
      uri: '{{ server }}'
      username: '{{ user }}'
      password: '{{ passwd }}'
      project: '{{ project }}'
      issue: '{{ item.issueid }}'
      operation: transition
      status: 'Declarar listo para pruebas'
    with_items:
      - '{{ tickets }}'
    register: issue
