---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
#  - include_vars: env.yml
  - name: Gather facts of instances
    ec2_instance_info:
#      aws_access_key: '{{ AWS_ACCESS_KEY_ID }}'
#      aws_secret_key: '{{ AWS_ACCESS_KEY }}'
#      security_token: '{{ AWS_SESSION_TOKEN }}'
      region: '{{ REGION }}'
      filters:
        instance-state-name: [ "running"]
    register: instances
