##############################################################################################
### For this playbook you need to change the env.yml file to connect to the target account  ##
### And change the tags to the ones you need                                                ##
##############################################################################################
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
#  - include_vars: env.yml
  - name: Gather facts of instances
    ec2_instance_info:
#      aws_access_key: '{{ AWS_ACCESS_KEY_ID }}'
#      aws_secret_key: '{{ AWS_ACCESS_KEY }}'
#      security_token: '{{ AWS_SESSION_TOKEN }}'
      region: '{{ REGION }}'
      filters:
        "tag:Name": '{{ filter }}'
        instance-state-name: [ "running"]
    register: instances
  - name: Ensure tags are present on a resource
    amazon.aws.ec2_tag:
#      aws_access_key: '{{ AWS_ACCESS_KEY_ID }}'
#      aws_secret_key: '{{ AWS_ACCESS_KEY }}'
#      security_token: '{{ AWS_SESSION_TOKEN }}'
      region: '{{ REGION }}'
      resource: '{{ item.instance_id }}'
      state: present
      tags:                 ## Ensure to put all the tags that you need ##
#        env: Prod
        'Backup Diario': 'si'
        Monitoring: 'win'
    with_items: "{{ instances.instances }}"
  - name: Terminate protection - Enable
    amazon.aws.ec2:
      aws_access_key: '{{ AWS_ACCESS_KEY_ID }}'
      aws_secret_key: '{{ AWS_ACCESS_KEY }}'
      security_token: '{{ AWS_SESSION_TOKEN }}'
      region: '{{ REGION }}'
      state: 'running'
      termination_protection: 'yes'
      instance_ids: '{{ item.instance_id }}'
    with_items: "{{ instances.instances }}"
